version: '3'

services:
  php:
    image: php:7.1-fpm-alpine
    volumes: 
      - ./src:/var/www/html
  nginx:
    build: docker/nginx #nginx:latest
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./confs/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/error.log:/var/log/nginx/error.log
      - ./logs/access.log:/var/log/nginx/access.log
      - ./src:/var/www/html
    command: [nginx-debug, '-g', 'daemon off;']
